// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/simple.dart';
import 'api/vtop/parser/faculty/parseabout.dart';
import 'api/vtop/parser/faculty/parsesearch.dart';
import 'api/vtop/parser/hostel/parseleave.dart';
import 'api/vtop/parser/hostel/parseoutings.dart';
import 'api/vtop/parser/parseattn.dart';
import 'api/vtop/parser/parsebiometric.dart';
import 'api/vtop/parser/parsegradehistory.dart';
import 'api/vtop/parser/parsemarks.dart';
import 'api/vtop/parser/parsepaymentreceipts.dart';
import 'api/vtop/parser/parsependingpayments.dart';
import 'api/vtop/parser/parseprofile.dart';
import 'api/vtop/parser/parsesched.dart';
import 'api/vtop/parser/parsett.dart';
import 'api/vtop/session_manager.dart';
import 'api/vtop/types/attendance.dart';
import 'api/vtop/types/biometric.dart';
import 'api/vtop/types/comprehensive_data.dart';
import 'api/vtop/types/exam_schedule.dart';
import 'api/vtop/types/faculty.dart';
import 'api/vtop/types/grade_course_history.dart';
import 'api/vtop/types/grade_history.dart';
import 'api/vtop/types/hostel.dart';
import 'api/vtop/types/marks.dart';
import 'api/vtop/types/mentor_details.dart';
import 'api/vtop/types/paid_payment_receipt.dart';
import 'api/vtop/types/pending_payment_receipt.dart';
import 'api/vtop/types/semester.dart';
import 'api/vtop/types/student_profile.dart';
import 'api/vtop/types/timetable.dart';
import 'api/vtop/vtop_client.dart';
import 'api/vtop/vtop_config.dart';
import 'api/vtop/vtop_errors.dart';
import 'api/vtop/wifi.dart';
import 'api/vtop_get_client.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'package:meta/meta.dart' as meta;

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ArcJarPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_SessionManagerPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_VtopClientPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopClientBuilderPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_VtopResultPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultFacultyDetailsPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFacultyDetails;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultGetFacultyPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGetFaculty;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultGradeHistoryVecGradeCourseHistoryPtr =>
          wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryVecGradeCourseHistory;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultHostelLeaveDataPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelLeaveData;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultHostelOutingDataPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelOutingData;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultSemesterDataPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultStringPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultString;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultStudentProfilePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultStudentProfile;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultVecAttendanceDetailRecordPtr =>
          wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceDetailRecord;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultVecAttendanceRecordPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceRecord;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultVecBiometricRecordPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecBiometricRecord;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultVecMarksRecordPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecMarksRecord;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultVecPaidPaymentReceiptPtr =>
          wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPaidPaymentReceipt;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultVecPendingPaymentReceiptPtr =>
          wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPendingPaymentReceipt;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultVecPerExamScheduleRecordPtr =>
          wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPerExamScheduleRecord;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultVecTimetableSlotPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecTimetableSlot;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VtopResultVecU8Ptr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8;

  @protected
  ArcJar
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
          dynamic raw);

  @protected
  SessionManager
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
          dynamic raw);

  @protected
  VtopClient
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
          dynamic raw);

  @protected
  VtopClientBuilder
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
          dynamic raw);

  @protected
  VtopResult
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
          dynamic raw);

  @protected
  VtopResultFacultyDetails
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFacultyDetails(
          dynamic raw);

  @protected
  VtopResultGetFaculty
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGetFaculty(
          dynamic raw);

  @protected
  VtopResultGradeHistoryVecGradeCourseHistory
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryVecGradeCourseHistory(
          dynamic raw);

  @protected
  VtopResultHostelLeaveData
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelLeaveData(
          dynamic raw);

  @protected
  VtopResultHostelOutingData
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelOutingData(
          dynamic raw);

  @protected
  VtopResultSemesterData
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
          dynamic raw);

  @protected
  VtopResultString
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultString(
          dynamic raw);

  @protected
  VtopResultStudentProfile
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultStudentProfile(
          dynamic raw);

  @protected
  VtopResultVecAttendanceDetailRecord
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceDetailRecord(
          dynamic raw);

  @protected
  VtopResultVecAttendanceRecord
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceRecord(
          dynamic raw);

  @protected
  VtopResultVecBiometricRecord
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecBiometricRecord(
          dynamic raw);

  @protected
  VtopResultVecMarksRecord
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecMarksRecord(
          dynamic raw);

  @protected
  VtopResultVecPaidPaymentReceipt
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPaidPaymentReceipt(
          dynamic raw);

  @protected
  VtopResultVecPendingPaymentReceipt
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPendingPaymentReceipt(
          dynamic raw);

  @protected
  VtopResultVecPerExamScheduleRecord
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPerExamScheduleRecord(
          dynamic raw);

  @protected
  VtopResultVecTimetableSlot
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecTimetableSlot(
          dynamic raw);

  @protected
  VtopResultVecU8
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
          dynamic raw);

  @protected
  SessionManager
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
          dynamic raw);

  @protected
  VtopClient
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
          dynamic raw);

  @protected
  SessionManager
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
          dynamic raw);

  @protected
  VtopClient
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
          dynamic raw);

  @protected
  ArcJar
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
          dynamic raw);

  @protected
  SessionManager
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
          dynamic raw);

  @protected
  VtopClient
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
          dynamic raw);

  @protected
  VtopClientBuilder
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
          dynamic raw);

  @protected
  VtopResult
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
          dynamic raw);

  @protected
  VtopResultFacultyDetails
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFacultyDetails(
          dynamic raw);

  @protected
  VtopResultGetFaculty
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGetFaculty(
          dynamic raw);

  @protected
  VtopResultGradeHistoryVecGradeCourseHistory
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryVecGradeCourseHistory(
          dynamic raw);

  @protected
  VtopResultHostelLeaveData
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelLeaveData(
          dynamic raw);

  @protected
  VtopResultHostelOutingData
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelOutingData(
          dynamic raw);

  @protected
  VtopResultSemesterData
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
          dynamic raw);

  @protected
  VtopResultString
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultString(
          dynamic raw);

  @protected
  VtopResultStudentProfile
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultStudentProfile(
          dynamic raw);

  @protected
  VtopResultVecAttendanceDetailRecord
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceDetailRecord(
          dynamic raw);

  @protected
  VtopResultVecAttendanceRecord
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceRecord(
          dynamic raw);

  @protected
  VtopResultVecBiometricRecord
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecBiometricRecord(
          dynamic raw);

  @protected
  VtopResultVecMarksRecord
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecMarksRecord(
          dynamic raw);

  @protected
  VtopResultVecPaidPaymentReceipt
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPaidPaymentReceipt(
          dynamic raw);

  @protected
  VtopResultVecPendingPaymentReceipt
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPendingPaymentReceipt(
          dynamic raw);

  @protected
  VtopResultVecPerExamScheduleRecord
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPerExamScheduleRecord(
          dynamic raw);

  @protected
  VtopResultVecTimetableSlot
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecTimetableSlot(
          dynamic raw);

  @protected
  VtopResultVecU8
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AttendanceDetailRecord dco_decode_attendance_detail_record(dynamic raw);

  @protected
  AttendanceRecord dco_decode_attendance_record(dynamic raw);

  @protected
  BiometricRecord dco_decode_biometric_record(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  VtopConfig dco_decode_box_autoadd_vtop_config(dynamic raw);

  @protected
  ComprehensiveDataResponse dco_decode_comprehensive_data_response(dynamic raw);

  @protected
  ExamScheduleRecord dco_decode_exam_schedule_record(dynamic raw);

  @protected
  FacultyDetails dco_decode_faculty_details(dynamic raw);

  @protected
  GetFaculty dco_decode_get_faculty(dynamic raw);

  @protected
  GradeCourseHistory dco_decode_grade_course_history(dynamic raw);

  @protected
  GradeHistory dco_decode_grade_history(dynamic raw);

  @protected
  HostelLeaveData dco_decode_hostel_leave_data(dynamic raw);

  @protected
  HostelOutingData dco_decode_hostel_outing_data(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  LeaveRecord dco_decode_leave_record(dynamic raw);

  @protected
  List<AttendanceDetailRecord> dco_decode_list_attendance_detail_record(
      dynamic raw);

  @protected
  List<AttendanceRecord> dco_decode_list_attendance_record(dynamic raw);

  @protected
  List<BiometricRecord> dco_decode_list_biometric_record(dynamic raw);

  @protected
  List<ExamScheduleRecord> dco_decode_list_exam_schedule_record(dynamic raw);

  @protected
  List<GradeCourseHistory> dco_decode_list_grade_course_history(dynamic raw);

  @protected
  List<LeaveRecord> dco_decode_list_leave_record(dynamic raw);

  @protected
  List<MarksRecord> dco_decode_list_marks_record(dynamic raw);

  @protected
  List<MarksRecordEach> dco_decode_list_marks_record_each(dynamic raw);

  @protected
  List<OfficeHour> dco_decode_list_office_hour(dynamic raw);

  @protected
  List<OutingRecord> dco_decode_list_outing_record(dynamic raw);

  @protected
  List<PaidPaymentReceipt> dco_decode_list_paid_payment_receipt(dynamic raw);

  @protected
  List<PendingPaymentReceipt> dco_decode_list_pending_payment_receipt(
      dynamic raw);

  @protected
  List<PerExamScheduleRecord> dco_decode_list_per_exam_schedule_record(
      dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SemesterInfo> dco_decode_list_semester_info(dynamic raw);

  @protected
  List<TimetableSlot> dco_decode_list_timetable_slot(dynamic raw);

  @protected
  MarksRecord dco_decode_marks_record(dynamic raw);

  @protected
  MarksRecordEach dco_decode_marks_record_each(dynamic raw);

  @protected
  MentorDetails dco_decode_mentor_details(dynamic raw);

  @protected
  OfficeHour dco_decode_office_hour(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  OutingRecord dco_decode_outing_record(dynamic raw);

  @protected
  PaidPaymentReceipt dco_decode_paid_payment_receipt(dynamic raw);

  @protected
  PendingPaymentReceipt dco_decode_pending_payment_receipt(dynamic raw);

  @protected
  PerExamScheduleRecord dco_decode_per_exam_schedule_record(dynamic raw);

  @protected
  (bool, String) dco_decode_record_bool_string(dynamic raw);

  @protected
  (GradeHistory, List<GradeCourseHistory>)
      dco_decode_record_grade_history_list_grade_course_history(dynamic raw);

  @protected
  SemesterData dco_decode_semester_data(dynamic raw);

  @protected
  SemesterInfo dco_decode_semester_info(dynamic raw);

  @protected
  StudentProfile dco_decode_student_profile(dynamic raw);

  @protected
  TimetableSlot dco_decode_timetable_slot(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VtopConfig dco_decode_vtop_config(dynamic raw);

  @protected
  VtopError dco_decode_vtop_error(dynamic raw);

  @protected
  ArcJar
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
          SseDeserializer deserializer);

  @protected
  SessionManager
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
          SseDeserializer deserializer);

  @protected
  VtopClient
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
          SseDeserializer deserializer);

  @protected
  VtopClientBuilder
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
          SseDeserializer deserializer);

  @protected
  VtopResult
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
          SseDeserializer deserializer);

  @protected
  VtopResultFacultyDetails
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFacultyDetails(
          SseDeserializer deserializer);

  @protected
  VtopResultGetFaculty
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGetFaculty(
          SseDeserializer deserializer);

  @protected
  VtopResultGradeHistoryVecGradeCourseHistory
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryVecGradeCourseHistory(
          SseDeserializer deserializer);

  @protected
  VtopResultHostelLeaveData
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelLeaveData(
          SseDeserializer deserializer);

  @protected
  VtopResultHostelOutingData
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelOutingData(
          SseDeserializer deserializer);

  @protected
  VtopResultSemesterData
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
          SseDeserializer deserializer);

  @protected
  VtopResultString
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultString(
          SseDeserializer deserializer);

  @protected
  VtopResultStudentProfile
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultStudentProfile(
          SseDeserializer deserializer);

  @protected
  VtopResultVecAttendanceDetailRecord
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceDetailRecord(
          SseDeserializer deserializer);

  @protected
  VtopResultVecAttendanceRecord
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceRecord(
          SseDeserializer deserializer);

  @protected
  VtopResultVecBiometricRecord
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecBiometricRecord(
          SseDeserializer deserializer);

  @protected
  VtopResultVecMarksRecord
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecMarksRecord(
          SseDeserializer deserializer);

  @protected
  VtopResultVecPaidPaymentReceipt
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPaidPaymentReceipt(
          SseDeserializer deserializer);

  @protected
  VtopResultVecPendingPaymentReceipt
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPendingPaymentReceipt(
          SseDeserializer deserializer);

  @protected
  VtopResultVecPerExamScheduleRecord
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPerExamScheduleRecord(
          SseDeserializer deserializer);

  @protected
  VtopResultVecTimetableSlot
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecTimetableSlot(
          SseDeserializer deserializer);

  @protected
  VtopResultVecU8
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
          SseDeserializer deserializer);

  @protected
  SessionManager
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
          SseDeserializer deserializer);

  @protected
  VtopClient
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
          SseDeserializer deserializer);

  @protected
  SessionManager
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
          SseDeserializer deserializer);

  @protected
  VtopClient
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
          SseDeserializer deserializer);

  @protected
  ArcJar
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
          SseDeserializer deserializer);

  @protected
  SessionManager
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
          SseDeserializer deserializer);

  @protected
  VtopClient
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
          SseDeserializer deserializer);

  @protected
  VtopClientBuilder
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
          SseDeserializer deserializer);

  @protected
  VtopResult
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
          SseDeserializer deserializer);

  @protected
  VtopResultFacultyDetails
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFacultyDetails(
          SseDeserializer deserializer);

  @protected
  VtopResultGetFaculty
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGetFaculty(
          SseDeserializer deserializer);

  @protected
  VtopResultGradeHistoryVecGradeCourseHistory
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryVecGradeCourseHistory(
          SseDeserializer deserializer);

  @protected
  VtopResultHostelLeaveData
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelLeaveData(
          SseDeserializer deserializer);

  @protected
  VtopResultHostelOutingData
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelOutingData(
          SseDeserializer deserializer);

  @protected
  VtopResultSemesterData
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
          SseDeserializer deserializer);

  @protected
  VtopResultString
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultString(
          SseDeserializer deserializer);

  @protected
  VtopResultStudentProfile
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultStudentProfile(
          SseDeserializer deserializer);

  @protected
  VtopResultVecAttendanceDetailRecord
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceDetailRecord(
          SseDeserializer deserializer);

  @protected
  VtopResultVecAttendanceRecord
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceRecord(
          SseDeserializer deserializer);

  @protected
  VtopResultVecBiometricRecord
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecBiometricRecord(
          SseDeserializer deserializer);

  @protected
  VtopResultVecMarksRecord
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecMarksRecord(
          SseDeserializer deserializer);

  @protected
  VtopResultVecPaidPaymentReceipt
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPaidPaymentReceipt(
          SseDeserializer deserializer);

  @protected
  VtopResultVecPendingPaymentReceipt
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPendingPaymentReceipt(
          SseDeserializer deserializer);

  @protected
  VtopResultVecPerExamScheduleRecord
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPerExamScheduleRecord(
          SseDeserializer deserializer);

  @protected
  VtopResultVecTimetableSlot
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecTimetableSlot(
          SseDeserializer deserializer);

  @protected
  VtopResultVecU8
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AttendanceDetailRecord sse_decode_attendance_detail_record(
      SseDeserializer deserializer);

  @protected
  AttendanceRecord sse_decode_attendance_record(SseDeserializer deserializer);

  @protected
  BiometricRecord sse_decode_biometric_record(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  VtopConfig sse_decode_box_autoadd_vtop_config(SseDeserializer deserializer);

  @protected
  ComprehensiveDataResponse sse_decode_comprehensive_data_response(
      SseDeserializer deserializer);

  @protected
  ExamScheduleRecord sse_decode_exam_schedule_record(
      SseDeserializer deserializer);

  @protected
  FacultyDetails sse_decode_faculty_details(SseDeserializer deserializer);

  @protected
  GetFaculty sse_decode_get_faculty(SseDeserializer deserializer);

  @protected
  GradeCourseHistory sse_decode_grade_course_history(
      SseDeserializer deserializer);

  @protected
  GradeHistory sse_decode_grade_history(SseDeserializer deserializer);

  @protected
  HostelLeaveData sse_decode_hostel_leave_data(SseDeserializer deserializer);

  @protected
  HostelOutingData sse_decode_hostel_outing_data(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  LeaveRecord sse_decode_leave_record(SseDeserializer deserializer);

  @protected
  List<AttendanceDetailRecord> sse_decode_list_attendance_detail_record(
      SseDeserializer deserializer);

  @protected
  List<AttendanceRecord> sse_decode_list_attendance_record(
      SseDeserializer deserializer);

  @protected
  List<BiometricRecord> sse_decode_list_biometric_record(
      SseDeserializer deserializer);

  @protected
  List<ExamScheduleRecord> sse_decode_list_exam_schedule_record(
      SseDeserializer deserializer);

  @protected
  List<GradeCourseHistory> sse_decode_list_grade_course_history(
      SseDeserializer deserializer);

  @protected
  List<LeaveRecord> sse_decode_list_leave_record(SseDeserializer deserializer);

  @protected
  List<MarksRecord> sse_decode_list_marks_record(SseDeserializer deserializer);

  @protected
  List<MarksRecordEach> sse_decode_list_marks_record_each(
      SseDeserializer deserializer);

  @protected
  List<OfficeHour> sse_decode_list_office_hour(SseDeserializer deserializer);

  @protected
  List<OutingRecord> sse_decode_list_outing_record(
      SseDeserializer deserializer);

  @protected
  List<PaidPaymentReceipt> sse_decode_list_paid_payment_receipt(
      SseDeserializer deserializer);

  @protected
  List<PendingPaymentReceipt> sse_decode_list_pending_payment_receipt(
      SseDeserializer deserializer);

  @protected
  List<PerExamScheduleRecord> sse_decode_list_per_exam_schedule_record(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SemesterInfo> sse_decode_list_semester_info(
      SseDeserializer deserializer);

  @protected
  List<TimetableSlot> sse_decode_list_timetable_slot(
      SseDeserializer deserializer);

  @protected
  MarksRecord sse_decode_marks_record(SseDeserializer deserializer);

  @protected
  MarksRecordEach sse_decode_marks_record_each(SseDeserializer deserializer);

  @protected
  MentorDetails sse_decode_mentor_details(SseDeserializer deserializer);

  @protected
  OfficeHour sse_decode_office_hour(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  OutingRecord sse_decode_outing_record(SseDeserializer deserializer);

  @protected
  PaidPaymentReceipt sse_decode_paid_payment_receipt(
      SseDeserializer deserializer);

  @protected
  PendingPaymentReceipt sse_decode_pending_payment_receipt(
      SseDeserializer deserializer);

  @protected
  PerExamScheduleRecord sse_decode_per_exam_schedule_record(
      SseDeserializer deserializer);

  @protected
  (bool, String) sse_decode_record_bool_string(SseDeserializer deserializer);

  @protected
  (GradeHistory, List<GradeCourseHistory>)
      sse_decode_record_grade_history_list_grade_course_history(
          SseDeserializer deserializer);

  @protected
  SemesterData sse_decode_semester_data(SseDeserializer deserializer);

  @protected
  SemesterInfo sse_decode_semester_info(SseDeserializer deserializer);

  @protected
  StudentProfile sse_decode_student_profile(SseDeserializer deserializer);

  @protected
  TimetableSlot sse_decode_timetable_slot(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VtopConfig sse_decode_vtop_config(SseDeserializer deserializer);

  @protected
  VtopError sse_decode_vtop_error(SseDeserializer deserializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
          ArcJar self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
          SessionManager self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
          VtopClient self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
          VtopClientBuilder self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
          VtopResult self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFacultyDetails(
          VtopResultFacultyDetails self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGetFaculty(
          VtopResultGetFaculty self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryVecGradeCourseHistory(
          VtopResultGradeHistoryVecGradeCourseHistory self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelLeaveData(
          VtopResultHostelLeaveData self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelOutingData(
          VtopResultHostelOutingData self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
          VtopResultSemesterData self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultString(
          VtopResultString self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultStudentProfile(
          VtopResultStudentProfile self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceDetailRecord(
          VtopResultVecAttendanceDetailRecord self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceRecord(
          VtopResultVecAttendanceRecord self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecBiometricRecord(
          VtopResultVecBiometricRecord self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecMarksRecord(
          VtopResultVecMarksRecord self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPaidPaymentReceipt(
          VtopResultVecPaidPaymentReceipt self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPendingPaymentReceipt(
          VtopResultVecPendingPaymentReceipt self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPerExamScheduleRecord(
          VtopResultVecPerExamScheduleRecord self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecTimetableSlot(
          VtopResultVecTimetableSlot self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
          VtopResultVecU8 self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
          SessionManager self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
          VtopClient self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
          SessionManager self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
          VtopClient self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
          ArcJar self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
          SessionManager self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
          VtopClient self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
          VtopClientBuilder self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
          VtopResult self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFacultyDetails(
          VtopResultFacultyDetails self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGetFaculty(
          VtopResultGetFaculty self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryVecGradeCourseHistory(
          VtopResultGradeHistoryVecGradeCourseHistory self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelLeaveData(
          VtopResultHostelLeaveData self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelOutingData(
          VtopResultHostelOutingData self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
          VtopResultSemesterData self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultString(
          VtopResultString self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultStudentProfile(
          VtopResultStudentProfile self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceDetailRecord(
          VtopResultVecAttendanceDetailRecord self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceRecord(
          VtopResultVecAttendanceRecord self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecBiometricRecord(
          VtopResultVecBiometricRecord self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecMarksRecord(
          VtopResultVecMarksRecord self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPaidPaymentReceipt(
          VtopResultVecPaidPaymentReceipt self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPendingPaymentReceipt(
          VtopResultVecPendingPaymentReceipt self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPerExamScheduleRecord(
          VtopResultVecPerExamScheduleRecord self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecTimetableSlot(
          VtopResultVecTimetableSlot self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
          VtopResultVecU8 self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_attendance_detail_record(
      AttendanceDetailRecord self, SseSerializer serializer);

  @protected
  void sse_encode_attendance_record(
      AttendanceRecord self, SseSerializer serializer);

  @protected
  void sse_encode_biometric_record(
      BiometricRecord self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vtop_config(
      VtopConfig self, SseSerializer serializer);

  @protected
  void sse_encode_comprehensive_data_response(
      ComprehensiveDataResponse self, SseSerializer serializer);

  @protected
  void sse_encode_exam_schedule_record(
      ExamScheduleRecord self, SseSerializer serializer);

  @protected
  void sse_encode_faculty_details(
      FacultyDetails self, SseSerializer serializer);

  @protected
  void sse_encode_get_faculty(GetFaculty self, SseSerializer serializer);

  @protected
  void sse_encode_grade_course_history(
      GradeCourseHistory self, SseSerializer serializer);

  @protected
  void sse_encode_grade_history(GradeHistory self, SseSerializer serializer);

  @protected
  void sse_encode_hostel_leave_data(
      HostelLeaveData self, SseSerializer serializer);

  @protected
  void sse_encode_hostel_outing_data(
      HostelOutingData self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_leave_record(LeaveRecord self, SseSerializer serializer);

  @protected
  void sse_encode_list_attendance_detail_record(
      List<AttendanceDetailRecord> self, SseSerializer serializer);

  @protected
  void sse_encode_list_attendance_record(
      List<AttendanceRecord> self, SseSerializer serializer);

  @protected
  void sse_encode_list_biometric_record(
      List<BiometricRecord> self, SseSerializer serializer);

  @protected
  void sse_encode_list_exam_schedule_record(
      List<ExamScheduleRecord> self, SseSerializer serializer);

  @protected
  void sse_encode_list_grade_course_history(
      List<GradeCourseHistory> self, SseSerializer serializer);

  @protected
  void sse_encode_list_leave_record(
      List<LeaveRecord> self, SseSerializer serializer);

  @protected
  void sse_encode_list_marks_record(
      List<MarksRecord> self, SseSerializer serializer);

  @protected
  void sse_encode_list_marks_record_each(
      List<MarksRecordEach> self, SseSerializer serializer);

  @protected
  void sse_encode_list_office_hour(
      List<OfficeHour> self, SseSerializer serializer);

  @protected
  void sse_encode_list_outing_record(
      List<OutingRecord> self, SseSerializer serializer);

  @protected
  void sse_encode_list_paid_payment_receipt(
      List<PaidPaymentReceipt> self, SseSerializer serializer);

  @protected
  void sse_encode_list_pending_payment_receipt(
      List<PendingPaymentReceipt> self, SseSerializer serializer);

  @protected
  void sse_encode_list_per_exam_schedule_record(
      List<PerExamScheduleRecord> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_semester_info(
      List<SemesterInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_timetable_slot(
      List<TimetableSlot> self, SseSerializer serializer);

  @protected
  void sse_encode_marks_record(MarksRecord self, SseSerializer serializer);

  @protected
  void sse_encode_marks_record_each(
      MarksRecordEach self, SseSerializer serializer);

  @protected
  void sse_encode_mentor_details(MentorDetails self, SseSerializer serializer);

  @protected
  void sse_encode_office_hour(OfficeHour self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_outing_record(OutingRecord self, SseSerializer serializer);

  @protected
  void sse_encode_paid_payment_receipt(
      PaidPaymentReceipt self, SseSerializer serializer);

  @protected
  void sse_encode_pending_payment_receipt(
      PendingPaymentReceipt self, SseSerializer serializer);

  @protected
  void sse_encode_per_exam_schedule_record(
      PerExamScheduleRecord self, SseSerializer serializer);

  @protected
  void sse_encode_record_bool_string(
      (bool, String) self, SseSerializer serializer);

  @protected
  void sse_encode_record_grade_history_list_grade_course_history(
      (GradeHistory, List<GradeCourseHistory>) self, SseSerializer serializer);

  @protected
  void sse_encode_semester_data(SemesterData self, SseSerializer serializer);

  @protected
  void sse_encode_semester_info(SemesterInfo self, SseSerializer serializer);

  @protected
  void sse_encode_student_profile(
      StudentProfile self, SseSerializer serializer);

  @protected
  void sse_encode_timetable_slot(TimetableSlot self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vtop_config(VtopConfig self, SseSerializer serializer);

  @protected
  void sse_encode_vtop_error(VtopError self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFacultyDetails(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFacultyDetails(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFacultyDetails(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFacultyDetails(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGetFaculty(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGetFaculty(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGetFaculty(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGetFaculty(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryVecGradeCourseHistory(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryVecGradeCourseHistory(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryVecGradeCourseHistory(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryVecGradeCourseHistory(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelLeaveData(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelLeaveData(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelLeaveData(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelLeaveData(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelOutingData(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelOutingData(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelOutingData(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelOutingData(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultString(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultString(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultString(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultString(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultStudentProfile(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultStudentProfile(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultStudentProfile(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultStudentProfile(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceDetailRecord(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceDetailRecord(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceDetailRecord(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceDetailRecord(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceRecord(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceRecord(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceRecord(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceRecord(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecBiometricRecord(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecBiometricRecord(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecBiometricRecord(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecBiometricRecord(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecMarksRecord(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecMarksRecord(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecMarksRecord(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecMarksRecord(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPaidPaymentReceipt(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPaidPaymentReceipt(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPaidPaymentReceipt(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPaidPaymentReceipt(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPendingPaymentReceipt(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPendingPaymentReceipt(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPendingPaymentReceipt(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPendingPaymentReceipt(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPerExamScheduleRecord(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPerExamScheduleRecord(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPerExamScheduleRecord(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPerExamScheduleRecord(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecTimetableSlot(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecTimetableSlot(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecTimetableSlot(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecTimetableSlot(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResult(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFacultyDetails(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultFacultyDetails(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGetFaculty(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGetFaculty(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryVecGradeCourseHistory(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultGradeHistoryVecGradeCourseHistory(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelLeaveData(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelLeaveData(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelOutingData(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultHostelOutingData(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultSemesterData(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultString(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultString(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultStudentProfile(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultStudentProfile(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceDetailRecord(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceDetailRecord(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceRecord(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecAttendanceRecord(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecBiometricRecord(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecBiometricRecord(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecMarksRecord(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecMarksRecord(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPaidPaymentReceipt(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPaidPaymentReceipt(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPendingPaymentReceipt(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPendingPaymentReceipt(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPerExamScheduleRecord(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecPerExamScheduleRecord(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecTimetableSlot(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecTimetableSlot(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopResultVecu8(
          int ptr);
}
