// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'package:meta/meta.dart' as meta;

import 'api/simple.dart';
import 'api/vtop/captcha_solver.dart';
import 'api/vtop/parser/attendance_parser.dart';
import 'api/vtop/parser/course_page_parser.dart';
import 'api/vtop/parser/digital_assignment_parser.dart';
import 'api/vtop/parser/exam_schedule_parser.dart';
import 'api/vtop/parser/faculty/parseabout.dart';
import 'api/vtop/parser/faculty/parsesearch.dart';
import 'api/vtop/parser/grade_history_parser.dart';
import 'api/vtop/parser/grade_view_parser.dart';
import 'api/vtop/parser/hostel/general_outing_parser.dart';
import 'api/vtop/parser/hostel/weekend_outing_parser.dart';
import 'api/vtop/parser/marks_parser.dart';
import 'api/vtop/parser/outing_form_parser.dart';
import 'api/vtop/parser/outing_response_parser.dart';
import 'api/vtop/parser/parse_biometric.dart';
import 'api/vtop/parser/payment_receipts_parser.dart';
import 'api/vtop/parser/pending_payments_parser.dart';
import 'api/vtop/parser/profile_parser.dart';
import 'api/vtop/parser/semested_id_parser.dart';
import 'api/vtop/parser/timetable_parser.dart';
import 'api/vtop/session_manager.dart';
import 'api/vtop/types/attendance.dart';
import 'api/vtop/types/biometric.dart';
import 'api/vtop/types/course_page.dart';
import 'api/vtop/types/digital_assignment.dart';
import 'api/vtop/types/exam_schedule.dart';
import 'api/vtop/types/faculty.dart';
import 'api/vtop/types/general_outing.dart';
import 'api/vtop/types/grade_course_history.dart';
import 'api/vtop/types/grade_history.dart';
import 'api/vtop/types/grade_view.dart';
import 'api/vtop/types/marks.dart';
import 'api/vtop/types/mentor_details.dart';
import 'api/vtop/types/outing_info.dart';
import 'api/vtop/types/paid_payment_receipt.dart';
import 'api/vtop/types/pending_payment_receipt.dart';
import 'api/vtop/types/semester.dart';
import 'api/vtop/types/student_profile.dart';
import 'api/vtop/types/timetable.dart';
import 'api/vtop/types/weekend_outing.dart';
import 'api/vtop/vtop_client.dart';
import 'api/vtop/vtop_config.dart';
import 'api/vtop/vtop_errors.dart';
import 'api/vtop_get_client.dart';
import 'frb_generated.dart';
import 'lib.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcJarPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJarPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ResponsePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponsePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SessionManagerPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManagerPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopClientPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VtopClientBuilderPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilderPtr;

  @protected
  ArcJar
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    dynamic raw,
  );

  @protected
  SessionManager
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    dynamic raw,
  );

  @protected
  VtopClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    dynamic raw,
  );

  @protected
  VtopClientBuilder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    dynamic raw,
  );

  @protected
  SessionManager
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    dynamic raw,
  );

  @protected
  VtopClient
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    dynamic raw,
  );

  @protected
  Response
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponse(
    dynamic raw,
  );

  @protected
  SessionManager
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    dynamic raw,
  );

  @protected
  VtopClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    dynamic raw,
  );

  @protected
  ArcJar
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    dynamic raw,
  );

  @protected
  Response
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponse(
    dynamic raw,
  );

  @protected
  SessionManager
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    dynamic raw,
  );

  @protected
  VtopClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    dynamic raw,
  );

  @protected
  VtopClientBuilder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AssignmentRecordEach dco_decode_assignment_record_each(dynamic raw);

  @protected
  AttendanceDetailRecord dco_decode_attendance_detail_record(dynamic raw);

  @protected
  AttendanceRecord dco_decode_attendance_record(dynamic raw);

  @protected
  BiometricRecord dco_decode_biometric_record(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  VtopConfig dco_decode_box_autoadd_vtop_config(dynamic raw);

  @protected
  VtopError dco_decode_box_autoadd_vtop_error(dynamic raw);

  @protected
  CourseClassEntry dco_decode_course_class_entry(dynamic raw);

  @protected
  CourseInfo dco_decode_course_info(dynamic raw);

  @protected
  CourseOption dco_decode_course_option(dynamic raw);

  @protected
  CoursePageDetail dco_decode_course_page_detail(dynamic raw);

  @protected
  CoursesResponse dco_decode_courses_response(dynamic raw);

  @protected
  DigitalAssignments dco_decode_digital_assignments(dynamic raw);

  @protected
  ExamScheduleRecord dco_decode_exam_schedule_record(dynamic raw);

  @protected
  FacultyDetails dco_decode_faculty_details(dynamic raw);

  @protected
  GeneralOutingRecord dco_decode_general_outing_record(dynamic raw);

  @protected
  GetFaculty dco_decode_get_faculty(dynamic raw);

  @protected
  GradeCourseHistory dco_decode_grade_course_history(dynamic raw);

  @protected
  GradeHistory dco_decode_grade_history(dynamic raw);

  @protected
  GradeRange dco_decode_grade_range(dynamic raw);

  @protected
  GradeStatistics dco_decode_grade_statistics(dynamic raw);

  @protected
  GradeViewCourse dco_decode_grade_view_course(dynamic raw);

  @protected
  GradeViewDetail dco_decode_grade_view_detail(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  LectureEntry dco_decode_lecture_entry(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AssignmentRecordEach> dco_decode_list_assignment_record_each(
    dynamic raw,
  );

  @protected
  List<AttendanceDetailRecord> dco_decode_list_attendance_detail_record(
    dynamic raw,
  );

  @protected
  List<AttendanceRecord> dco_decode_list_attendance_record(dynamic raw);

  @protected
  List<BiometricRecord> dco_decode_list_biometric_record(dynamic raw);

  @protected
  List<CourseClassEntry> dco_decode_list_course_class_entry(dynamic raw);

  @protected
  List<CourseOption> dco_decode_list_course_option(dynamic raw);

  @protected
  List<DigitalAssignments> dco_decode_list_digital_assignments(dynamic raw);

  @protected
  List<ExamScheduleRecord> dco_decode_list_exam_schedule_record(dynamic raw);

  @protected
  List<GeneralOutingRecord> dco_decode_list_general_outing_record(dynamic raw);

  @protected
  List<GetFaculty> dco_decode_list_get_faculty(dynamic raw);

  @protected
  List<GradeCourseHistory> dco_decode_list_grade_course_history(dynamic raw);

  @protected
  List<GradeRange> dco_decode_list_grade_range(dynamic raw);

  @protected
  List<GradeViewCourse> dco_decode_list_grade_view_course(dynamic raw);

  @protected
  List<LectureEntry> dco_decode_list_lecture_entry(dynamic raw);

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw);

  @protected
  List<MarkComponent> dco_decode_list_mark_component(dynamic raw);

  @protected
  List<Marks> dco_decode_list_marks(dynamic raw);

  @protected
  List<MarksRecordEach> dco_decode_list_marks_record_each(dynamic raw);

  @protected
  List<OfficeHour> dco_decode_list_office_hour(dynamic raw);

  @protected
  List<PaidPaymentReceipt> dco_decode_list_paid_payment_receipt(dynamic raw);

  @protected
  List<PendingPaymentReceipt> dco_decode_list_pending_payment_receipt(
    dynamic raw,
  );

  @protected
  List<PerExamScheduleRecord> dco_decode_list_per_exam_schedule_record(
    dynamic raw,
  );

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReferenceMaterial> dco_decode_list_reference_material(dynamic raw);

  @protected
  List<SemesterInfo> dco_decode_list_semester_info(dynamic raw);

  @protected
  List<SlotOption> dco_decode_list_slot_option(dynamic raw);

  @protected
  List<TimetableClass> dco_decode_list_timetable_class(dynamic raw);

  @protected
  List<WeekendOutingRecord> dco_decode_list_weekend_outing_record(dynamic raw);

  @protected
  MarkComponent dco_decode_mark_component(dynamic raw);

  @protected
  Marks dco_decode_marks(dynamic raw);

  @protected
  MarksRecordEach dco_decode_marks_record_each(dynamic raw);

  @protected
  MentorDetails dco_decode_mentor_details(dynamic raw);

  @protected
  OfficeHour dco_decode_office_hour(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  OutingInfo dco_decode_outing_info(dynamic raw);

  @protected
  PaidPaymentReceipt dco_decode_paid_payment_receipt(dynamic raw);

  @protected
  PendingPaymentReceipt dco_decode_pending_payment_receipt(dynamic raw);

  @protected
  PerExamScheduleRecord dco_decode_per_exam_schedule_record(dynamic raw);

  @protected
  ReferenceMaterial dco_decode_reference_material(dynamic raw);

  @protected
  SemesterData dco_decode_semester_data(dynamic raw);

  @protected
  SemesterInfo dco_decode_semester_info(dynamic raw);

  @protected
  SlotOption dco_decode_slot_option(dynamic raw);

  @protected
  SlotsResponse dco_decode_slots_response(dynamic raw);

  @protected
  StudentProfile dco_decode_student_profile(dynamic raw);

  @protected
  Timetable dco_decode_timetable(dynamic raw);

  @protected
  TimetableClass dco_decode_timetable_class(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VtopConfig dco_decode_vtop_config(dynamic raw);

  @protected
  VtopError dco_decode_vtop_error(dynamic raw);

  @protected
  WeekendOutingRecord dco_decode_weekend_outing_record(dynamic raw);

  @protected
  ArcJar
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    SseDeserializer deserializer,
  );

  @protected
  SessionManager
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    SseDeserializer deserializer,
  );

  @protected
  VtopClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    SseDeserializer deserializer,
  );

  @protected
  VtopClientBuilder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    SseDeserializer deserializer,
  );

  @protected
  SessionManager
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    SseDeserializer deserializer,
  );

  @protected
  VtopClient
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    SseDeserializer deserializer,
  );

  @protected
  Response
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponse(
    SseDeserializer deserializer,
  );

  @protected
  SessionManager
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    SseDeserializer deserializer,
  );

  @protected
  VtopClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    SseDeserializer deserializer,
  );

  @protected
  ArcJar
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    SseDeserializer deserializer,
  );

  @protected
  Response
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponse(
    SseDeserializer deserializer,
  );

  @protected
  SessionManager
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    SseDeserializer deserializer,
  );

  @protected
  VtopClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    SseDeserializer deserializer,
  );

  @protected
  VtopClientBuilder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AssignmentRecordEach sse_decode_assignment_record_each(
    SseDeserializer deserializer,
  );

  @protected
  AttendanceDetailRecord sse_decode_attendance_detail_record(
    SseDeserializer deserializer,
  );

  @protected
  AttendanceRecord sse_decode_attendance_record(SseDeserializer deserializer);

  @protected
  BiometricRecord sse_decode_biometric_record(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  VtopConfig sse_decode_box_autoadd_vtop_config(SseDeserializer deserializer);

  @protected
  VtopError sse_decode_box_autoadd_vtop_error(SseDeserializer deserializer);

  @protected
  CourseClassEntry sse_decode_course_class_entry(SseDeserializer deserializer);

  @protected
  CourseInfo sse_decode_course_info(SseDeserializer deserializer);

  @protected
  CourseOption sse_decode_course_option(SseDeserializer deserializer);

  @protected
  CoursePageDetail sse_decode_course_page_detail(SseDeserializer deserializer);

  @protected
  CoursesResponse sse_decode_courses_response(SseDeserializer deserializer);

  @protected
  DigitalAssignments sse_decode_digital_assignments(
    SseDeserializer deserializer,
  );

  @protected
  ExamScheduleRecord sse_decode_exam_schedule_record(
    SseDeserializer deserializer,
  );

  @protected
  FacultyDetails sse_decode_faculty_details(SseDeserializer deserializer);

  @protected
  GeneralOutingRecord sse_decode_general_outing_record(
    SseDeserializer deserializer,
  );

  @protected
  GetFaculty sse_decode_get_faculty(SseDeserializer deserializer);

  @protected
  GradeCourseHistory sse_decode_grade_course_history(
    SseDeserializer deserializer,
  );

  @protected
  GradeHistory sse_decode_grade_history(SseDeserializer deserializer);

  @protected
  GradeRange sse_decode_grade_range(SseDeserializer deserializer);

  @protected
  GradeStatistics sse_decode_grade_statistics(SseDeserializer deserializer);

  @protected
  GradeViewCourse sse_decode_grade_view_course(SseDeserializer deserializer);

  @protected
  GradeViewDetail sse_decode_grade_view_detail(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  LectureEntry sse_decode_lecture_entry(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AssignmentRecordEach> sse_decode_list_assignment_record_each(
    SseDeserializer deserializer,
  );

  @protected
  List<AttendanceDetailRecord> sse_decode_list_attendance_detail_record(
    SseDeserializer deserializer,
  );

  @protected
  List<AttendanceRecord> sse_decode_list_attendance_record(
    SseDeserializer deserializer,
  );

  @protected
  List<BiometricRecord> sse_decode_list_biometric_record(
    SseDeserializer deserializer,
  );

  @protected
  List<CourseClassEntry> sse_decode_list_course_class_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<CourseOption> sse_decode_list_course_option(
    SseDeserializer deserializer,
  );

  @protected
  List<DigitalAssignments> sse_decode_list_digital_assignments(
    SseDeserializer deserializer,
  );

  @protected
  List<ExamScheduleRecord> sse_decode_list_exam_schedule_record(
    SseDeserializer deserializer,
  );

  @protected
  List<GeneralOutingRecord> sse_decode_list_general_outing_record(
    SseDeserializer deserializer,
  );

  @protected
  List<GetFaculty> sse_decode_list_get_faculty(SseDeserializer deserializer);

  @protected
  List<GradeCourseHistory> sse_decode_list_grade_course_history(
    SseDeserializer deserializer,
  );

  @protected
  List<GradeRange> sse_decode_list_grade_range(SseDeserializer deserializer);

  @protected
  List<GradeViewCourse> sse_decode_list_grade_view_course(
    SseDeserializer deserializer,
  );

  @protected
  List<LectureEntry> sse_decode_list_lecture_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer);

  @protected
  List<MarkComponent> sse_decode_list_mark_component(
    SseDeserializer deserializer,
  );

  @protected
  List<Marks> sse_decode_list_marks(SseDeserializer deserializer);

  @protected
  List<MarksRecordEach> sse_decode_list_marks_record_each(
    SseDeserializer deserializer,
  );

  @protected
  List<OfficeHour> sse_decode_list_office_hour(SseDeserializer deserializer);

  @protected
  List<PaidPaymentReceipt> sse_decode_list_paid_payment_receipt(
    SseDeserializer deserializer,
  );

  @protected
  List<PendingPaymentReceipt> sse_decode_list_pending_payment_receipt(
    SseDeserializer deserializer,
  );

  @protected
  List<PerExamScheduleRecord> sse_decode_list_per_exam_schedule_record(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReferenceMaterial> sse_decode_list_reference_material(
    SseDeserializer deserializer,
  );

  @protected
  List<SemesterInfo> sse_decode_list_semester_info(
    SseDeserializer deserializer,
  );

  @protected
  List<SlotOption> sse_decode_list_slot_option(SseDeserializer deserializer);

  @protected
  List<TimetableClass> sse_decode_list_timetable_class(
    SseDeserializer deserializer,
  );

  @protected
  List<WeekendOutingRecord> sse_decode_list_weekend_outing_record(
    SseDeserializer deserializer,
  );

  @protected
  MarkComponent sse_decode_mark_component(SseDeserializer deserializer);

  @protected
  Marks sse_decode_marks(SseDeserializer deserializer);

  @protected
  MarksRecordEach sse_decode_marks_record_each(SseDeserializer deserializer);

  @protected
  MentorDetails sse_decode_mentor_details(SseDeserializer deserializer);

  @protected
  OfficeHour sse_decode_office_hour(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  OutingInfo sse_decode_outing_info(SseDeserializer deserializer);

  @protected
  PaidPaymentReceipt sse_decode_paid_payment_receipt(
    SseDeserializer deserializer,
  );

  @protected
  PendingPaymentReceipt sse_decode_pending_payment_receipt(
    SseDeserializer deserializer,
  );

  @protected
  PerExamScheduleRecord sse_decode_per_exam_schedule_record(
    SseDeserializer deserializer,
  );

  @protected
  ReferenceMaterial sse_decode_reference_material(SseDeserializer deserializer);

  @protected
  SemesterData sse_decode_semester_data(SseDeserializer deserializer);

  @protected
  SemesterInfo sse_decode_semester_info(SseDeserializer deserializer);

  @protected
  SlotOption sse_decode_slot_option(SseDeserializer deserializer);

  @protected
  SlotsResponse sse_decode_slots_response(SseDeserializer deserializer);

  @protected
  StudentProfile sse_decode_student_profile(SseDeserializer deserializer);

  @protected
  Timetable sse_decode_timetable(SseDeserializer deserializer);

  @protected
  TimetableClass sse_decode_timetable_class(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VtopConfig sse_decode_vtop_config(SseDeserializer deserializer);

  @protected
  VtopError sse_decode_vtop_error(SseDeserializer deserializer);

  @protected
  WeekendOutingRecord sse_decode_weekend_outing_record(
    SseDeserializer deserializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    ArcJar self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    SessionManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    VtopClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    VtopClientBuilder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    SessionManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    VtopClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponse(
    Response self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    SessionManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    VtopClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    ArcJar self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponse(
    Response self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    SessionManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    VtopClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    VtopClientBuilder self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_assignment_record_each(
    AssignmentRecordEach self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_attendance_detail_record(
    AttendanceDetailRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_attendance_record(
    AttendanceRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_biometric_record(
    BiometricRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vtop_config(
    VtopConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_vtop_error(
    VtopError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_course_class_entry(
    CourseClassEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_course_info(CourseInfo self, SseSerializer serializer);

  @protected
  void sse_encode_course_option(CourseOption self, SseSerializer serializer);

  @protected
  void sse_encode_course_page_detail(
    CoursePageDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_courses_response(
    CoursesResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_digital_assignments(
    DigitalAssignments self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_exam_schedule_record(
    ExamScheduleRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_faculty_details(
    FacultyDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_general_outing_record(
    GeneralOutingRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_get_faculty(GetFaculty self, SseSerializer serializer);

  @protected
  void sse_encode_grade_course_history(
    GradeCourseHistory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_grade_history(GradeHistory self, SseSerializer serializer);

  @protected
  void sse_encode_grade_range(GradeRange self, SseSerializer serializer);

  @protected
  void sse_encode_grade_statistics(
    GradeStatistics self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_grade_view_course(
    GradeViewCourse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_grade_view_detail(
    GradeViewDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_lecture_entry(LectureEntry self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_assignment_record_each(
    List<AssignmentRecordEach> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_attendance_detail_record(
    List<AttendanceDetailRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_attendance_record(
    List<AttendanceRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_biometric_record(
    List<BiometricRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_course_class_entry(
    List<CourseClassEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_course_option(
    List<CourseOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_digital_assignments(
    List<DigitalAssignments> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_exam_schedule_record(
    List<ExamScheduleRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_general_outing_record(
    List<GeneralOutingRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_get_faculty(
    List<GetFaculty> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_grade_course_history(
    List<GradeCourseHistory> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_grade_range(
    List<GradeRange> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_grade_view_course(
    List<GradeViewCourse> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_lecture_entry(
    List<LectureEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mark_component(
    List<MarkComponent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_marks(List<Marks> self, SseSerializer serializer);

  @protected
  void sse_encode_list_marks_record_each(
    List<MarksRecordEach> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_office_hour(
    List<OfficeHour> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_paid_payment_receipt(
    List<PaidPaymentReceipt> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pending_payment_receipt(
    List<PendingPaymentReceipt> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_per_exam_schedule_record(
    List<PerExamScheduleRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reference_material(
    List<ReferenceMaterial> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_semester_info(
    List<SemesterInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_slot_option(
    List<SlotOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_timetable_class(
    List<TimetableClass> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_weekend_outing_record(
    List<WeekendOutingRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mark_component(MarkComponent self, SseSerializer serializer);

  @protected
  void sse_encode_marks(Marks self, SseSerializer serializer);

  @protected
  void sse_encode_marks_record_each(
    MarksRecordEach self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mentor_details(MentorDetails self, SseSerializer serializer);

  @protected
  void sse_encode_office_hour(OfficeHour self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_outing_info(OutingInfo self, SseSerializer serializer);

  @protected
  void sse_encode_paid_payment_receipt(
    PaidPaymentReceipt self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pending_payment_receipt(
    PendingPaymentReceipt self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_per_exam_schedule_record(
    PerExamScheduleRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reference_material(
    ReferenceMaterial self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semester_data(SemesterData self, SseSerializer serializer);

  @protected
  void sse_encode_semester_info(SemesterInfo self, SseSerializer serializer);

  @protected
  void sse_encode_slot_option(SlotOption self, SseSerializer serializer);

  @protected
  void sse_encode_slots_response(SlotsResponse self, SseSerializer serializer);

  @protected
  void sse_encode_student_profile(
    StudentProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timetable(Timetable self, SseSerializer serializer);

  @protected
  void sse_encode_timetable_class(
    TimetableClass self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vtop_config(VtopConfig self, SseSerializer serializer);

  @protected
  void sse_encode_vtop_error(VtopError self, SseSerializer serializer);

  @protected
  void sse_encode_weekend_outing_record(
    WeekendOutingRecord self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJarPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_vit_ap_student_app_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJarPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJarPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_vit_ap_student_app_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJar =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcJarPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponse(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponse(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponsePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_vit_ap_student_app_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponse',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponse =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponsePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponse(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponse(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponsePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_vit_ap_student_app_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponse',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponse =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResponsePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManagerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_vit_ap_student_app_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManagerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManagerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_vit_ap_student_app_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManager =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionManagerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_vit_ap_student_app_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_vit_ap_student_app_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClient =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_vit_ap_student_app_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_vit_ap_student_app_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilder =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVtopClientBuilderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
