# Generated code do not commit.
file(TO_CMAKE_PATH "/home/user/flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "/home/user/vitap_student_app" PROJECT_DIR)

set(FLUTTER_VERSION "2.1.0+12" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 2 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 0 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 12 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=/home/user/flutter"
  "PROJECT_DIR=/home/user/vitap_student_app"
  "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuMzIuMC0wLjIucHJl,RkxVVFRFUl9DSEFOTkVMPWJldGE=,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049ZDNhYmQwMGU2OQ==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049MzgyYmUwMDI4ZA==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My44LjAgKGJ1aWxkIDMuOC4wLTI3OC4xLmJldGEp"
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=true"
  "PACKAGE_CONFIG=/home/user/vitap_student_app/.dart_tool/package_config.json"
  "FLUTTER_TARGET=lib/main.dart"
)
