// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'attendance.dart';
import 'exam_schedule.dart';
import 'grade_course_history.dart';
import 'grade_history.dart';
import 'marks.dart';
import 'mentor_details.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;
import 'student_profile.dart';
import 'timetable.dart';
part 'comprehensive_data.freezed.dart';
part 'comprehensive_data.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Comprehensive response containing all student data in a single structure.
/// This includes profile, attendance, timetable, exam schedule, grade history, and marks.
@freezed
@meta.immutable
sealed class ComprehensiveDataResponse with _$ComprehensiveDataResponse {
  const factory ComprehensiveDataResponse({
    required StudentProfile profile,
    required List<AttendanceRecord> attendance,
    required List<TimetableSlot> timetable,
    required List<PerExamScheduleRecord> examSchedule,
    required List<GradeCourseHistory> gradeCourseHistory,
    required List<MarksRecord> marks,
  }) = _ComprehensiveDataResponse;

  factory ComprehensiveDataResponse.fromJson(Map<String, dynamic> json) =>
      _$ComprehensiveDataResponseFromJson(json);
}
