// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;
part 'hostel.freezed.dart';
part 'hostel.g.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `OutingFormData`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

@freezed
@meta.immutable
sealed class HostelLeaveData with _$HostelLeaveData {
  const factory HostelLeaveData({
    required List<LeaveRecord> records,
    required BigInt updateTime,
  }) = _HostelLeaveData;

  factory HostelLeaveData.fromJson(Map<String, dynamic> json) =>
      _$HostelLeaveDataFromJson(json);
}

@freezed
@meta.immutable
sealed class HostelOutingData with _$HostelOutingData {
  const factory HostelOutingData({
    required List<OutingRecord> records,
    required BigInt updateTime,
  }) = _HostelOutingData;

  factory HostelOutingData.fromJson(Map<String, dynamic> json) =>
      _$HostelOutingDataFromJson(json);
}

@freezed
@meta.immutable
sealed class LeaveRecord with _$LeaveRecord {
  const factory LeaveRecord({
    required String serial,
    required String registrationNumber,
    required String placeOfVisit,
    required String purposeOfVisit,
    required String fromDate,
    required String fromTime,
    required String toDate,
    required String toTime,
    required String status,
    required bool canDownload,
    required String leaveId,
  }) = _LeaveRecord;

  factory LeaveRecord.fromJson(Map<String, dynamic> json) =>
      _$LeaveRecordFromJson(json);
}

@freezed
@meta.immutable
sealed class OutingRecord with _$OutingRecord {
  const factory OutingRecord({
    required String serial,
    required String registrationNumber,
    required String hostelBlock,
    required String roomNumber,
    required String placeOfVisit,
    required String purposeOfVisit,
    required String time,
    required String contactNumber,
    required String parentContactNumber,
    required String date,
    required String bookingId,
    required String status,
    required bool canDownload,
  }) = _OutingRecord;

  factory OutingRecord.fromJson(Map<String, dynamic> json) =>
      _$OutingRecordFromJson(json);
}
